### ISSUE TITLE
DocGen generating JavaDoc style, not ScalaDoc style comments

### ISSUE THREAD

**Issue by julianpeeters** [eed3si9n/treehugger#30]
Hi again,

I notice that treehugger produces JavaDoc style when I believe the intent is to produce ScalaDoc style. [Treehugger's documentation] shows the issue: (http://eed3si9n.com/treehugger/comments.html#Scaladoc+style+comments), while here is the [ScalaDoc spec](http://docs.scala-lang.org/style/scaladoc.html).

The differences that ScalaDoc adopts seem to be: 
1) Text always begins on the first line, after /**
2) "*"s that begin new comment lines in multiline comments should be aligned in the 3rd column rather than the second.

Not really sure this is a pressing issue. I'd suspect that JavaDoc style is pretty compatible with most  ScalaDoc parsers (?). Also, it appears that intellij seems to have the same issue (using JavaDoc style for ScalaDocs), and that doesn't seem to cause much trouble.

So not really an issue for me, but I thought I should report this.

**Comment by eed3si9n** [comment]
Thanks for the report.

**Comment by eed3si9n** [comment]
+1 on fixing this. I'd accept PR for this if you're up for it.

**Comment by julianpeeters** [comment]
Yup, I'll take a swing.

**Comment by eed3si9n** [comment]
I've since then looked into the ScalaDoc styling, and came to conclusion that "JavaDoc" style should be the standard. See https://github.com/scalameta/scalafmt/issues/891


- Style Guide http://docs.scala-lang.org/style/scaladoc.html recommends the "JavaDoc" style.
- Many of the OSS projects use the "JavaDoc" style. Here are some random sampling:
   - https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
   - https://github.com/akka/akka/blob/v2.5.0/akka-actor/src/main/scala/akka/actor/Actor.scala
   - https://github.com/scalatest/scalatest/blob/release-3.0.2/scalatest/src/main/scala/org/scalatest/FlatSpec.scala
   - https://github.com/typelevel/cats/blob/v0.9.0/core/src/main/scala/cats/Monad.scala

**Comment by julianpeeters** [comment]
:+1:

**Comment by eed3si9n** [comment]
Closing this.
