### ISSUE TITLE
Create scala 2.13 treehugger release

### ISSUE THREAD

**Issue by derabbink** [eed3si9n/treehugger#55]
Scala 2.13 was released [on June 7th][1], and it would be super nice to also see a corresponding treehugger release.

I'd consider chipping in in making this happen, but at he minute I don't have enough information at my fingertips to know how to get to a PR for such a version bump. Any help/information about when a release like this might be out, or how I could help getting there would be much appreciated.

Thanks in advance!

[1]: https://github.com/scala/scala/releases/tag/v2.13.0

**Comment by eed3si9n** [comment]
> I'd consider chipping in in making this happen, but at he minute I don't have enough information at my fingertips to know how to get to a PR for such a version bump. Any help/information about when a release like this might be out, or how I could help getting there would be much appreciated.

I am already working it, so I don't need help for this but since you asked how you could have helped, it would be pretty straight forward if you've ever worked in any Scala program. Look into build.sbt, and try bumping it to Scala 2.13, and update Spec2, and try to work on any compilation errors or deprecations.

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/treehugger/releases/tag/v0.4.4
